### ISSUE TITLE
Implement hands on tables component

### ISSUE THREAD

**Issue by starsinmypockets** [datopian/datapackage-views-js#1]
## Description
Hands on tables will be used for resource preview

## Tasks
- [x] Implement table component
- [x] Test with dataset resource
- [x] Integrate with application structure
- [x] Add test

**Comment by anuveyatsu** [comment]
@starsinmypockets let's call it just "Table" because handsontable is just a library we're using but it can be replaced any time if we find better library

**Comment by anuveyatsu** [comment]
@starsinmypockets I've setup some tests here, do you think they're sufficient so we can close this issue? 

https://github.com/datopian/datapackage-views-js/blob/master/src/App.test.js#L38-L49
