### ISSUE TITLE
Table component improvements

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datapackage-views-js#10]
## User stories

* As a User, I want to be able to read full column names even if it is very long so that I can understand what it is about.
  * Eg, there are lots of situations when the dataset has lots of columns so we cannot display everything fully.

https://handsontable.com/docs/7.1.0/demo-header-tooltips.html

* As a User, I want to be able to change the order of the columns so that I can put the columns that are important for me next to each other.

https://handsontable.com/docs/7.1.0/demo-moving.html

* As a User, I want to be able to resize a column width so that I can preview the data in a better way.

https://handsontable.com/docs/7.1.0/demo-resizing.html

## Acceptance criteria

* [x] User stories are completed

## Tasks

* [x] Analysis of how and where we should implement it
* [x] Display the header label in a tooltip
* [x] Moving the columns
* [ ] ~~Resizing the columns~~
  * already implemented

## Analysis

We could make these as our default options for Table component. We could implement it in the `datapackage-render-js` library:

https://github.com/frictionlessdata/datapackage-render-js/blob/master/lib/view.js#L128-L168

Since we're going to make it a default options, we can hard code the settings in the returning object.

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/datapackage-render-js/commit/c71392afefea2d0e34e6cd8781d49aedb8d1787f
