### ISSUE TITLE
Map component

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datapackage-views-js#12]
As a User, I want to have a preview of geojson files so that I understand what it is about without downloading it and rendering it (so I save time, it has better UX and the site looks better).

As a Publisher, I want my website to render a preview of geojson files so that my visitors can get more insights.

## Acceptance criteria

* [x] my geographical data is rendered as a map on showcase page

## Tasks

* [x] create `Map` component
* [x] handle data loading process
* [x] handle rendering the component in `App.js`
* [x] add fixtures for cosmos
* [x] add tests

**Comment by anuveyatsu** [comment]
FIXED, can't give an example link as we don't have working GeoJSON resource. But feel free to check it out in Cosmos under `Map` component.
