### ISSUE TITLE
Document component

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datapackage-views-js#13]
As a User, I want to preview documents (eg PDF) on the data portal so that I can understand what it is about (as I don't want to download unknown files + I don't have PDF viewer).

As a Publisher, I want to have previews of the documents that I'm publishing so that my visitors can see it, learn it and get insights.

## Acceptance criteria

* [x] I can preview PDF resources on showcase page

## Tasks

* [x] analysis of how we load it
  * leave it for pdf module
* [x] add `Document` component
* [x] add fixtures for cosmos so we can test first
* [x] implement data loading
* [x] add unit tests

**Comment by anuveyatsu** [comment]
FIXED but no support for `png` file, should it be? @starsinmypockets
