### ISSUE TITLE
Spinner

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datapackage-views-js#14]
As a User, I want to see a spinner while data is loading so that I have a sense of what's going on (eg, sometimes I don't know what to expect - is it going to render anything?).

As a Publisher, I want to have a spinner on my data portal while data is loading so that my visitors don't leave the page without waiting for data previews.

## Acceptance criteria

* [x] I can see the spinner while the data is loading

## Tasks

* [ ] update the unit tests
* [x] update fixtures for cosmos
* [ ] implement Spinner component
* [x] show the spinner when data is loading

**Comment by anuveyatsu** [comment]
FIXED - data fether is moved to Data Explorer app and now this app only receives `loading` props and shows spinner based on that.
