### ISSUE TITLE
Process data package identifier

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datapackage-views-js#2]
## Acceptance criteria

* [x] I can pass a `DP_ID` and the app loads a Dataset object from it
* [x] In the loaded Dataset object, I have File object per resource with inlined data (e.g., in `_values` property)

## Tasks

* [x] load Dataset object using data.js
* [x] get rows of each Resource object using data.js

**Comment by anuveyatsu** [comment]
FIXED, see the tests here for 3 cases:

https://github.com/datopian/datapackage-views-js/blob/master/src/App.test.js
