### ISSUE TITLE
Document public interface

### ISSUE THREAD

**Issue by starsinmypockets** [datopian/datapackage-views-js#21]
As a user I want to know how to use this library so I can use it

### Acceptance

- [ ] New user can instantiate component from docs

### Tasks
- [ ] Figure out what the public interface is and document in analysis section, below
- [ ] Add quick public interface to docs

### Analysis

Something like:

## Getting started
In index.js:

```javascript=
import React from 'react'
import ReactDom from 'react-dom'
import DataView from ''datapackage-views-js"

ReactDom.render(<DataView datapackge={views: {resource: [{a: 1, b: 2}, {a: 2, b:2}, specType: 'table', title: 'Linear data']} />, // get el)
```
