### ISSUE TITLE
Define proptypes

### ISSUE THREAD

**Issue by starsinmypockets** [datopian/datapackage-views-js#22]
As a developer I want the proptypes declaration to guide my use of the component so I know what to pass to the component

### Tasks

- [ ] read up on proptypes
- [ ] enable proptypes lib
- [ ] define proptypes

### Acceptance

- [ ] exported component has proptypes declaration
