### ISSUE TITLE
View compilation and conversion

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datapackage-views-js#3]
## Acceptance criteria

* [x] I have compiled views with converted specs, e.g.,
  * [x] my Table view is ready to be rendered

## Tasks

* [x] call datapackage-render-js library for each view (only tables for now)
* [ ] tests

**Comment by starsinmypockets** [comment]
I will add these tests today

**Comment by anuveyatsu** [comment]
Part of the tests are covered already in eg https://github.com/datopian/datapackage-views-js/blob/master/src/App.test.js#L38-L49

Another part of it is located in `src/index.js` - problem is that this module doesn't export anything which is easily testable.

I will do some research/analysis and try to add some tests for it.

**Comment by anuveyatsu** [comment]
Not needed anymore since most of the process was moved to Data Explorer app. `index.js` is now used only for public interface.
