### ISSUE TITLE
Add horizontal-bar type

### ISSUE THREAD

**Issue by EvgeniiaVak** [datopian/datapackage-views-js#32]
## Acceptance criteria

* [ ] there is a "horizontal-bar" type for the simple spec which renders into a horizontal bar chart

## Tasks

* [ ] add the ability to pass "horizontal-bar" type to the simple spec
* [ ] handle "group" and "series" properties differently for the "horizontal-bar" type

**Comment by EvgeniiaVak** [comment]
DUPLICATE.
https://github.com/frictionlessdata/datapackage-render-js/issues/53
