### ISSUE TITLE
Add Plotly Spec

### ISSUE THREAD

**Issue by EvgeniiaVak** [datopian/datapackage-views-js#33]
## Acceptance criteria

* [x] The datapackage-views-js accepts "plotly" as a `specType` and renders it with an official Plotly library

## Tasks

* [x] Create a utility function to get data from resources - https://github.com/frictionlessdata/datapackage-render-js/issues/55
* [x]  Add "plotly" as a `specType`
* [x] Add plotly fixture

## Analysis

Our `simple` spec is converted to `plotly` spec and then passed to Plotly (Chart) component which renders a graph from it:

https://github.com/datopian/datapackage-views-js/blob/master/src/App.js#L67-L80

To support `plotly` spec directly we need to do something similar but with different "helper" funciton, e.g., `plotlyToPlotly` or similar. That function is needed to compile data from a resource.

Note that `Chart` component should remain unchanged so that simple spec works as before.

**Comment by anuveyatsu** [comment]
@EvgeniiaVak just updated issue description with some quick analysis.
