### ISSUE TITLE
[Epic] Datapackage-views-js v0.0.1

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datapackage-views-js#4]
## Acceptance criteria

* [x] I have the working app that renders a Table component with the tabular data
* [x] I can use it in my frontend-v2 app

## Tasks

* [x] Implement `Table` component - #1 
* [x] Set up test datasets on demo.ckan.org - #7 
* [x] Impement loading dataset - #2 
* [x] Implement view compilation and spec conversion - #3 
* [x] Wire up everything so the app works
* [x] Set up Travis for CI - #5 
* [x] Set up test coverage report - #6

**Comment by starsinmypockets** [comment]
@anuveyatsu See https://github.com/datopian/datapackage-views-js/pull/9

**Comment by anuveyatsu** [comment]
FIXED, working demo is here https://frontend-v2-openddk.herokuapp.com/city-of-copenhagen/afmaerkning_total
