### ISSUE TITLE
Add translations for React Table component

### ISSUE THREAD

**Issue by EvgeniiaVak** [datopian/datapackage-views-js#41]
One of the dependencies - [react-table-v6](https://www.npmjs.com/package/react-table-v6) - contains the following strings:
```
  previousText: 'Previous',
  nextText: 'Next',
  loadingText: 'Loading...',
  noDataText: 'No rows found',
  pageText: 'Page',
  ofText: 'of',
  rowsText: 'rows',
```

## Acceptance criteria

* [ ] Tranlsations supported: `en`, `da`, `fr`
* [ ] All the strings from react-table-v6 are rendered in the correct language among supported (determined by `defaulLocale` cookie)

## Tasks

* [ ] Translate the strings for `react-table-v6` library, they are extracted to [the props](https://www.npmjs.com/package/react-table-v6#props) to `en`, `da`, `fr`
* [ ] Translate every other string to `fr` (they are already translated to `en` and `da`)
