### ISSUE TITLE
[EPIC] datapackage-views-js - UI / UX Improvements

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datapackage-views-js#44]
Moved from gitlab. Originally created by @starsinmypockets 

## Description
We have implemented a first working version of the preview library. Do analysis and determine next round of UX / UI improvements.

- [ ] Add resource metadata to preview
  - [ ] filename
  - [ ] file format
  - [ ] size
  - [ ] ...
- [ ] Add file format to preview with icon: PDF / CSV / GEOJSON / JSON / UNKNOWN / ...
- [ ] Loading Spinner
- [ ] If data will not load, do not show preview message
![image](/uploads/d50747a69ba539f23bc30348fea6da85/image.png)
eg from Montreal (http://localhost:4000/ville-de-montreal/secteur-deneigement#resource-secteur_de_d%C3%A9neigement_-_saison_2017-2018)
- [ ] Analyze failed loads:
  - [ ] Failure cases
    - [ ] Very large files
  - [ ] Implement timeout?
  - [ ] UX questions - how much info on failures do we show user
  - [ ] how can we capture relevant info on preview failures for development / iteration / improvement
- [ ] Some resources do not load as expected 
  - [ ] (eg: http://localhost:4000/ville-de-montreal/info-collectes)
- [ ] Shut down stream after preview set is loaded (related to: https://github.com/datopian/data.js/issues/55)
