### ISSUE TITLE
Set up Travis build for CI

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datapackage-views-js#5]
## Acceptance criteria

* [x] I have Travis triggering a build on each commit

## Tasks

* [x] Create `.travis.yml` instructions - can be minimal, e.g., `yarn` and then `yarn test`
* [x] Set it up on Travis platform
* [x] Add a badge in the README

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datopian/datapackage-views-js/commit/a43ee8bddc4ee1ef6f09859f8db6bc0e2dce8281
