### ISSUE TITLE
Set up test coverage report

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datapackage-views-js#6]
## Acceptance criteria

* [x] I have a badge in the README telling me the current test coverage rate

## Tasks

* [ ] install `nyc` and update `package.json` so that all tests go through it
  * must not be `nyc` see what's the easiest/recommended for Create-react-app
* [ ] update `.travis.yml` if necessary
* [ ] set it up on Coveralls platform
* [ ] add a badge in the README

**Comment by starsinmypockets** [comment]
@anuveyatsu Do you have a solution in mind for testing?

**Comment by anuveyatsu** [comment]
@starsinmypockets i guess this is now fixed? If so please update this issue.

**Comment by starsinmypockets** [comment]
@anuveyatsu Handled this a little differently see: https://github.com/datopian/datapackage-views-js/pull/11

**Comment by starsinmypockets** [comment]
https://github.com/datopian/datapackage-views-js/pull/11
