### ISSUE TITLE
Set up test datasets on CKAN

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datapackage-views-js#7]
## Acceptance criteria

* [ ] I have test datasets for testing our app

## Tasks

* [ ] create 2 datasets (good enough and large enough for tests) on demo.ckan.org
  * [ ] have one of them with more than 1 CSV resource

**Comment by anuveyatsu** [comment]
@svetozarstojkovic can you please update this issue and close it?

**Comment by svetozarstojkovic** [comment]
Datasets:
1. [CO2 PPM - Trends in Atmospheric Carbon Dioxide ](https://demo.ckan.org/dataset/co2-ppm-trends-in-atmospheric-carbon-dioxide)
2. [Global Average Absolute Sea Level Change, 1880-2014 ](https://demo.ckan.org/dataset/global-average-absolute-sea-level-change-1880-2014)
