### ISSUE TITLE
Customizable headers for Table component

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datapackage-views-js#8]
As X, I want to see headers in the preview table in a human-readable and descriptive format so that I can understand it well without further research.

Original ticket title:

> Possibility to have display names separate from db column names

Original ticket description:

> DB column name is the same as column header giving some very nasty column headers in preview. We would like to be able to specify a display name different from the DB column name to be used in preview.

E.g., in the Datastore, they have column name "aFRR_DownActivated" which they want to display as "aFRR Downward regulation activated".

## Acceptance criteria

* [x] I have a way of displaying nice column names instead of what comes from the data source

## Tasks

* [x] Analysis
* [x] ~~Implement in Table component~~
  * [x] implement in datapackage-render-js lib
* [x] test

## Analysis

Since we're moving towards Data Packages protocol, we can utilize `title` property of a field descriptor in tableschema:

```json=
{
  "name": "aFRR_DownActivated",
  "title": "aFRR Downward regulation activated",
  "type": "A string specifying the type",
  "format": "A string specifying a format",
  "description": "A description for the field",
  "constraints": {
      // a constraints-descriptor
  }
}
```

So if a schema is provided, we should look at titles of the fields and use it to display preview table's headers. If a schema isn't provided, then we just use headers (field names).

This can be done in datapackage-render-js library when we convert table spec:

https://github.com/frictionlessdata/datapackage-render-js/blob/master/lib/view.js#L128

// OLD

In `Table.js` component, we should be able to pass a list of headers so that in props we have 2 attributes:

* `headers` - e.g., `["header1", "header2", ..., "headerN"]`
* `rows` - the data itself

**Comment by starsinmypockets** [comment]
I will add test today

**Comment by anuveyatsu** [comment]
@starsinmypockets just to make it clear - this only needs tests since the implementation is already done

**Comment by anuveyatsu** [comment]
FIXED - if a schema is provided, the titles of fields are used as table headers.
